### PR TITLE
slicesfix: fix incorrect slices lenghts

### LINKED ISSUE #2: ReadTo() causes audio artifacts
Seems like this line [`s = s[:len(data)-1]`](https://github.com/alttagil/sonic-go/blob/main/api.go#L159C2-L159C21) causes audio artifacts.

### PR DESCRIPTION
**Pull request by alttagil**
This PR addresses an issue with how output data slices are handled. Previously, the code used to = to[:len(data)-1], which incorrectly excluded the last byte from the output slice. The corrected approach is to use to = to[:len(data)] to ensure that the entire slice of copied data is included.

This fix ensures that all the bytes read into the slice are correctly reflected in the output.

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -36,11 +36,11 @@ func ChangeSpeed(sampleRate, numChannels int, speed, pitch, rate, volume float64
 	if cap(samples) < len(out) {
 		samples = make([]int16, len(out))
 	} else {
-		samples = samples[:len(out)-1]
+		samples = samples[:len(out)]
 	}
 
 	n := copy(samples, out)
-	return samples[:n-1], nil
+	return samples[:n], nil
```
Comment (millfort) [inline api.go]: до этого sample и out делаются одинаковой длинны, лишняя операция

File: sonic_test.go [hunk 2]
```diff
@@ -242,7 +242,7 @@ func findPitchPeriodInRangeNativeA(b *SampleBuffer, minP, maxP int) (int, int, i
 	maxDiff = 0
 	samples, _ := b.GetSlice(2 * maxP)
 
-	_ = samples[len(samples)-1]
+	_ = samples[len(samples)]
```
Comment (millfort) [inline sonic_test.go]: Лишнее

File: sonic_test.go [hunk 3]
```diff
@@ -279,7 +279,7 @@ func findPitchPeriodInRangeNative(b *SampleBuffer, minP, maxP int) (int, int, in
...
```
Comment (millfort) [inline sonic_test.go]: Лишнее

File: sonic_test.go [hunk 4]
```diff
@@ -319,7 +319,7 @@ func findPitchPeriodInRangeNativeAbs(b *SampleBuffer, minP, maxP int) (int, int,
...
```
Comment (millfort) [inline sonic_test.go]: Лишнее

**Review by millfort — CHANGES_REQUESTED** [review]

**Review by millfort — APPROVED** [review]
